/*----- PROTECTED REGION ID(Device2Class.h) ENABLED START -----*/
//=============================================================================
//
// file :        Device2Class.h
//
// description : Include for the Device2 root class.
//               This class is the singleton class for
//                the Device2 device class.
//               It contains all properties and methods which the 
//               Device2 requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Device2Class_H
#define Device2Class_H

#include <tango.h>
#include <Device2.h>


/*----- PROTECTED REGION END -----*/	//	Device2Class.h


namespace Device2_ns
{
/*----- PROTECTED REGION ID(Device2Class::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	Device2Class::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute attr2 class definition
class attr2Attrib: public Tango::Attr
{
public:
	attr2Attrib():Attr("attr2",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~attr2Attrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<Device2 *>(dev))->read_attr2(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<Device2 *>(dev))->is_attr2_allowed(ty);}
};


/**
 *	The Device2Class singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  Device2Class : public Tango::DeviceClass
#else
class Device2Class : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(Device2Class::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	Device2Class::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static Device2Class *init(const char *);
		static Device2Class *instance();
		~Device2Class();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		Device2Class(string &);
		static Device2Class *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	Device2_H
