/*----- PROTECTED REGION ID(Device2StateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        Device2StateMachine.cpp
//
// description : State machine file for the Device2 class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Device2.h>

/*----- PROTECTED REGION END -----*/	//	Device2::Device2StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Device2_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Device2::is_attr2_allowed()
 *	Description : Execution allowed for attr2 attribute
 */
//--------------------------------------------------------
bool Device2::is_attr2_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for attr2 attribute in read access.
	/*----- PROTECTED REGION ID(Device2::attr2StateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Device2::attr2StateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(Device2::Device2StateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Device2::Device2StateAllowed.AdditionalMethods

}	//	End of namespace
